name: CI Pipeline

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Build with Maven
      run: mvn clean package

    - name: Run SonarQube Analysis
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
        mvn sonar:sonar \
          -Dsonar.projectKey=TALSAGI1_hello-world-war \
          https://sonarcloud.io=http://localhost:9000 \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}

    - name: Build Docker Image
      run: |
        docker build -t hello-world-war:${{ github.run_id }} .
        echo "Docker image tagged with build ID: ${{ github.run_id }}"

    - name: Tag Docker Image
      run: |
        docker tag hello-world-war:${{ github.run_id }} <ghcr.io/TALSAGI1/hello-world-war>/hello-world-war:${{ github.run_id }}
        docker push <ghcr.io/TALSAGI1/hello-world-war>/hello-world-war:${{ github.run_id }}
